// import React from "react";
// function Questionlist(){
const questions=[
    {question: "1.Who created React?",
     options:[
        {id:"Google",value:"google"},
        {id:"Meta",value:"meta"},
        {id:"Facebook",value:"facebook"},
        {id:"Microsoft",value:"Microsoft"},
    ],
     answer:2,
    },
    {question: "2. What is ReactJS?",
    options:[
        {id:"Server-side framework",value:"server-side framework"},
        {id:"User interface framework",value:"user interface framework"},
        {id:"Both",value:"both"},
        {id:"None",value:"none"},
    ],
     answer:1,
    },
    {question: "3.Who created React.js?",
    options:[
        {id:"Jordan Mike",value:"jordan mike"},
        {id:"Jordan Walke",value:"jordan walke"},
        {id:"Tim Lee",value:"tim Lee"},
        {id:"Jordan Lee",value:"jordan Lee"},
    ],
     answer:1,
    },
    {question: "4.In which language is React.js written?",
    options:[
        {id:"Python",value:"python"},
        {id:"Javascript",value:"javascript"},
        {id:"Java",value:"java"},
        {id:"HTML",value:"html"},
    ],
     answer:1,
    },
    {question: "5.What is Babel?",
    options:[
        {id:"JS compiler",value:"JS compiler"},
        {id:"JS interpreter",value:"JS interpreter"},
        {id:"JS transpiler",value:"JS transpiler"},
        {id:"None",value:"None"},
    ],
     answer:0,
    },
    {question: "6.Identify the command used to create a react app.",
    options:[
        {id:"npm install create-react-app",value:"npm install create-react-app"},
        {id:"npm install -g create-react-app",value:"npm install -g create-react-app"},
        {id:"npm -g create-react-app",value:"npm -g create-react-app"},
        {id:"None",value:"none"},
    ],
     answer:0,
    },
    {question: "7.Which of the following port is the default where webpack-dev-server runs?",
    options:[
        {id:"3000",value:"3000"},
        {id:"3001",value:"3001"},
        {id:"3006",value:"3006"},
        {id:"8080",value:"8080"},
    ],
     answer:0,
    },
    {question: "8.A state in React.js is also known as?",
    options:[
        {id:"Internal storage",value:"internal storage"},
        {id:"External storage",value:"External storage"},
        {id:"Permanent storage",value:"permanent storage"},
        {id:"None",value:"none"},
    ],
     answer:0,
    },
    {question: "9. What are arbitrary inputs of components in react also known as?",
    options:[
        {id:"Props",value:"props"},
        {id:"Elements",value:"elements"},
        {id:"Keys",value:"keys"},
        {id:"Ref",value:"ref"},
    ],
     answer:0,
    },
    {question: "10.Identify the smallest building block of React.JS.",
    options:[
        {id:"Props",value:"props"},
        {id:"Elements",value:"elements"},
        {id:"Keys",value:"keys"},
        {id:"Components",value:"components"},
    ],
     answer:3,
    }
    ]
// }
    export default questions;

